=== muaz3406/xmljaxparser/ogrenci.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.w3.org.com/ogrenci" 
	xmlns:tns="http://www.w3.org.com/ogrenci"
	elementFormDefault="qualified">
	<!-- adres complexType -->
	<xs:complexType name="adresTipi">
		<xs:sequence>
		<xs:element name="il" type="xs:string"> </xs:element>
		<xs:element name="ilce" type="xs:string"></xs:element>
		</xs:sequence>
	</xs:complexType>
	<!-- dersTipi -->
	<xs:complexType name="dersler">
	<xs:sequence>
	<xs:element name="ders" type="xs:string" minOccurs="1" 
	maxOccurs="100"></xs:element>
	</xs:sequence>
	</xs:complexType>
	<!-- ogrenciTipi -->
	<xs:complexType name="ogrenciTipi">
	<xs:sequence>
	<xs:element name="ad" type="xs:string"></xs:element>
	<xs:element name="soyad" type="xs:string"></xs:element>
	<xs:element name="yas" type="xs:byte"></xs:element>
	<xs:element name="adres" type="tns:adresTipi"></xs:element>
	<xs:element name="dersler" type="tns:dersler"></xs:element>
	</xs:sequence>
	<xs:attribute name="no" type="xs:integer"></xs:attribute>
	</xs:complexType>
	<!-- ogrenciletipi -->
	<xs:complexType name="ogrencilerTipi">
	<xs:sequence>
	<xs:element name="ogrenci" type="tns:ogrenciTipi"
	minOccurs="1" maxOccurs="100"></xs:element>
	</xs:sequence>
	</xs:complexType>
<!-- root/ogrenciler eleman -->
<xs:element name="ogrenciler" type="tns:ogrencilerTipi"></xs:element>
 </xs:schema>

=== muaz3406/xmljaxparser/ogrenci.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:ogrenciler xmlns:tns="http://www.w3.org/ogrenci" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.w3.org.com/ogrenci ogrenci.xsd ">
  <ogrenci no="1">
    <ad>faik</ad>
    <soyad>turan</soyad>
    <yas>40</yas>
    <adres>
      <il>istanbul</il>
      <ilce>avcılar</ilce>
    </adres>
    <dersler>
      <ders>matematik</ders>
      <ders>fizik</ders>
      <ders>kimya</ders>
      <ders>edebiyat</ders>
    </dersler>
  </ogrenci>
  <ogrenci no="2">
    <ad>ali</ad>
    <soyad>gel</soyad>
    <yas>30</yas>
    <adres>
      <il>istanbul</il>
      <ilce>pendik</ilce>
    </adres>
    <dersler>
      <ders>matematik</ders>
      <ders>fizik</ders>
      <ders>kimya</ders>
      <ders>edebiyat</ders>
    </dersler>
  </ogrenci>
  <ogrenci no="3">
    <ad>veli</ad>
    <soyad>git</soyad>
    <yas>35</yas>
    <adres>
      <il>istanbul</il>
      <ilce>kadıköy</ilce>
    </adres>
    <dersler>
      <ders>matematik</ders>
      <ders>fizik</ders>
      <ders>kimya</ders>
      <ders>edebiyat</ders>
    </dersler>
  </ogrenci>
  <ogrenci no="4">
    <ad>ayşe</ad>
    <soyad>koç</soyad>
    <yas>25</yas>
    <adres>
      <il>istanbul</il>
      <ilce>maltepe</ilce>
    </adres>
    <dersler>
      <ders>matematik</ders>
      <ders>fizik</ders>
      <ders>kimya</ders>
      <ders>edebiyat</ders>
    </dersler>
  </ogrenci>
</tns:ogrenciler>
